### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Zjemm** [dlenski/network-manager-openconnect#1]
Hi,

i'm allready using your openconnect for palo alto adition on the CLI but wanted some simple gui and found you are working on it :)

i pulled this network manager from git, but how do i install it?

i ran the autogen but got this message:
./autogen.sh: line 17: intltoolize: command not found

Also i was wondering if your openconnect implementation supports token based authentication.
i'm now using a cert and password authentication, but working with softtokens from e.g. safenet would be much nicer

in the help there is:
Using GnuTLS. Features present: PKCS#11, HOTP software token, TOTP software token, System keys, DTLS
      --token-mode=MODE           Software token type: rsa, totp or hotp
      --token-secret=STRING       Software token secret
                                  (NOTE: libstoken (RSA SecurID) disabled in this build)

Let me hear what you think

**Comment by dlenski** [comment]
See https://github.com/dlenski/openconnect/issues/20 … I don't have the time or inclination to work on making this easy to install until the relevant changes are accepted into the OpenConnect API.

**Comment by Zjemm** [comment]
ok, we will see what the future brings.
thanks for replying
