### ISSUE TITLE
How to build and install the plugin

### ISSUE THREAD

**Issue by Joseluismantilla** [dlenski/network-manager-openconnect#6]
I would like to have the steps to building and installation process with Centos 7 or Fedora to do the correct installation, please.

**Comment by dlenski** [comment]
See #5.

This simply isn't going to be easy to build or install in an integrated way until it's merged into the mainline and picked up by distributions.

**Comment by mattgen88** [comment]
I can't seem to get this working either
cloned repo, on branch multiprotocol
./autogen.sh and installed dependencies
./configure
make
sudo make install

everything seems fine, then I restart NetworkManager
Navigate to the vpn dialog
I see the openconnect options now
I select openconnect and only have an option from juniper/pulse and anyconnect, no palo alto which is what I need

Is there a way forward with this, especially with your changes getting merged into openconnect 8.0.0? I hate having a dedicated terminal running my VPN

**Comment by dlenski** [comment]
> I select openconnect and only have an option from juniper/pulse and anyconnect, no palo alto which is what I need

What version of OpenConnect do you have installed, exactly?

If you're building against OpenConnect v8.0+ (API v5.5+), then the plugin gets the list of supported protocols from the library: https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/blob/master/properties/nm-openconnect-editor-plugin.c#L391-403

I suspect that you must be building against an older version of openconnect, where the list of supported protocols is hardcoded.

**Comment by mattgen88** [comment]
I've built and installed 8.02 and have been using the cli for a bit now

I'll dig more. I might be doing something dumb

**Comment by giogam** [comment]
I've been trying to build the plugin for Ubuntu 19.10 but autogen.sh keeps failing witn the following error

> checking for LIBNM_GLIB... no
> configure: error: Package requirements (NetworkManager >= 1.2.0
> 			libnm-util >= 1.2.0
> 			libnm-glib >= 1.2.0
> 			libnm-glib-vpn >= 1.2.0) were not met:
> 
> No package 'NetworkManager' found
> No package 'libnm-util' found
> No package 'libnm-glib' found
> No package 'libnm-glib-vpn' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables LIBNM_GLIB_CFLAGS
> and LIBNM_GLIB_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> 

openconnect version should be fine

> OpenConnect version v8.02-1build1
> Using GnuTLS. Features present: TPMv2, PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
> Supported protocols: anyconnect (default), nc, gp

When trying to install the missing packages it seems that they have been removed/substituted

> sudo apt install libnm-util-dev libnm-glib-dev libnm-glib-vpn-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package libnm-glib-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package libnm-glib-vpn-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package libnm-util-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libnm-util-dev' has no installation candidate
> E: Package 'libnm-glib-dev' has no installation candidate
> E: Package 'libnm-glib-vpn-dev' has no installation candidate

Any advice on how to fix this issue? I can help if needed

## Update ##
I'v been able to successfully build and install the plugin with the `--without-libnm-glib` but I still don't see the third option

**Comment by heshammhafez** [comment]
Did anyone manage to know the reason why it's not appearing after successful build. I used openconnect v 8.08 on elementaryOS it's based on ubuntu but didn't appear too. I tested paloalto VPN connection using cli and worked fine.
