### ISSUE TITLE
Set vpn0 as default route

### ISSUE THREAD

**Issue by YangtseSu** [dlenski/network-manager-openconnect#8]
After enable the VPN.
I must do "sudo ip route add default dev vpn0" to set vpn0 as default route.
Is this can be the default option?

**Comment by dlenski** [comment]
> Is this can be the default option?

This sounds like a vpnc-script issue. What makes you think it has something to do with the NetworkManager plugin?

**Comment by YangtseSu** [comment]
It works when using openconnect in command line.
But I should change the route when use NM plugin.

You are too harsh on the end user. I am not a programmer, I can not understand the source code.I can't tell where this bug came from.

**Comment by dlenski** [comment]
> I can't tell where this bug came from.

I can't either. I doubt it is a bug in the repository that you are reporting on, but _I am not a mind reader_ and I can't say much more than that from your brief description, with no context.

> You are too harsh on the end user. I am not a programmer, I can not understand the source code.I can't tell where this bug came from.

No one is paying me to write, debug, support, or maintain this code.

If you want help solving this problem, you should think carefully about what information a developer might need to help you solve it.

- What operating system are you running?
- What version of openconnect are you running? (`openconnect --version`)
- What version of this repository are you running? (commit ID)
- What kind of VPN protocol are you connecting to?
- Where does your vpnc-script come from?
- What does your routing table look like when connecting with OC from the command line? What does it look like when connecting via NetworkManager? Do you observe any other differences?
- What relevant information have you found in log files and debugging output?
