### ISSUE TITLE
set gid0: Operation not permitted

### ISSUE THREAD

**Issue by matmo** [dlenski/network-manager-openconnect#9]
When using a CSD wrapper script in nm-openconnect the connection fails with a setgid error.

NetworkManager debug log:
```
NetworkManager: Creating SSL connection failed
openconnect: HIP script '/opt/hipreport.sh' returned non-zero status: 1
NetworkManager: Failed to set gid 0: Operation not permitted
openconnect: POST https://$IP/ssl-vpn/hipreportcheck.esp
openconnect: No MTU received. Calculated 1403 for SSL tunnel. No ESP keys received
```

nm-openconnect-service --debug:
```
nm-openconnect <warn>  Created tundev vpn0
nm-openconnect <info>  openconnect started with pid 7867
Failed to set gid 0: Operation not permitted
Creating SSL connection failed
nm-openconnect <warn>  openconnect exited with error code 1
nm-openconnect <warn>  Destroyed  tundev vpn0
```

What I have tried:

* [x] Running openconnect manually (works)
* [x] Using a dumb CSD script with return 1
* [x] Changing file permissions
* [x] Using upstream versions (openconnect 0.8, ...)

I stumbled upon [this discussion](https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/commit/c8479b244f27ea31204a86a0c2800b447964e0aa#4080dfabe2d785dd06cbfaeb4b91a6ad6bc3b27c_481_490) but am not sure if it is related.

Thanks for your work on this, let me know if I can provide more debugging info.

**Comment by dlenski** [comment]
> I stumbled upon [this discussion](https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/commit/c8479b244f27ea31204a86a0c2800b447964e0aa#4080dfabe2d785dd06cbfaeb4b91a6ad6bc3b27c_481_490) but am not sure if it is related.

I believe you are right.

Unfortunately, I'm in a bit over my head here and don't actually have a good environment for building and testing my changes myself right now. :man_facepalming:

**Comment by dlenski** [comment]
See https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/-/issues/38 and https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/-/merge_requests/2
